# Generated by Django 4.0.3 on 2022-03-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('license_plate', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=255)),
            ],
        ),
    ]
