# Generated by Django 4.0.3 on 2022-03-21 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='model_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(choices=[('RPM', 'Rpm'), ('SPEED', 'Speed'), ('coolant_temperature', 'Coolant Temperature'), ('throttle_position', 'Throttle Position'), ('fuel_level', 'Fuel Level'), ('engine_oil_temperature', 'Engine Oil Temperature')], max_length=25)),
                ('data', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rest_api.vehicle')),
            ],
        ),
    ]
