# Generated by Django 4.0.2 on 2022-03-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_alter_vehicle_model_name_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='sensor',
            field=models.CharField(choices=[('rpm', 'Rpm'), ('speed', 'Speed'), ('coolant_temperature', 'Coolant Temperature'), ('throttle_position', 'Throttle Position'), ('fuel_level', 'Fuel Level'), ('engine_oil_temperature', 'Engine Oil Temperature'), ('engine_load', 'Engine Load'), ('fuel_rail_gauge', 'Engine Fuel Gauge'), ('intake_air_temperature', 'Intake Air Temperature'), ('intake_manifold_pressure', 'Intake Manifold Pressure')], max_length=25),
        ),
    ]
