# Generated by Django 4.0.3 on 2022-04-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_alter_measurement_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='anomalous',
            field=models.BooleanField(default=False),
        ),
    ]
