# Generated by Django 4.0.3 on 2022-04-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_measurement_anomalous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='sensor',
            field=models.CharField(choices=[('rpm', 'Rpm'), ('speed', 'Speed'), ('coolant_temperature', 'Coolant Temperature'), ('throttle_position', 'Throttle Position'), ('fuel_level', 'Fuel Level'), ('engine_oil_temperature', 'Engine Oil Temperature'), ('engine_load', 'Engine Load'), ('fuel_rail_gauge', 'Engine Fuel Gauge'), ('intake_air_temperature', 'Intake Air Temperature'), ('intake_manifold_pressure', 'Intake Manifold Pressure'), ('front_right_wheel', 'Front Right Wheel'), ('front_left_wheel', 'Front Left Wheel'), ('rear_right_wheel', 'Rear Right Wheel'), ('rear_left_wheel', 'Rear Left Wheel')], max_length=25),
        ),
    ]
